---
title: "Lab 8"
author: "Madeline Berger"
date: "5/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(rgdal)
library(rasterVis)
library(maps)
library(rgeos)
library(tidyverse)
library(RColorBrewer)

# view some color palettes
# display.brewer.all()
# rainbow color scheme
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) 

#setting smaller margins for plotting
par(mar=c(2,2,1,1))



# view some color palettes
# display.brewer.all()
# rainbow color scheme
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) 

#setting smaller margins for plotting
par(mar=c(2,2,1,1))

all_threats <- raster("full_modelnv.tif")

```

####Notes from class 

General 
raster comes with simple basemaps in "map" function

Plotting 
Extent argument allows you to zoom into a region, the numbers after refer to lat and long (or whatever spatial reference units your data is in) 


```{r}

#Creating plots to visualize data

plot(all_threats,col=cols)

# add a landmap to your shapefile. the add=T argument tells R to add it to the existing plot.
# make sure you understand what the other arguments do
plot(all_threats,ext=extent(-130,-110,24,50),col=cols)
map('world',fill=T,add=T,col='gray')



plot(all_threats,col=cols,ext=extent(-121,-117,32,35),main="Cumulative Threats") # A good extent for the Santa Barbara Channel
map('world',fill=T,add=T,col='gray')

# Creating a histogram to look at value distribution

hist(all_threats,main="Cumulative Threats Frequency")

# Using cellStates to present summary statistics, in this case: mean, sd.

cellStats(all_threats,mean)
cellStats(all_threats,sd)


```

```{r}

all_spp <- raster("ca_curr_sp_rich.tif")

```



