---
title: "ourturn_shipping"
author: "Madeline Berger"
date: "5/29/2019"
output: html_document
---

```{r setup, include=FALSE}

library(raster)
library(rgdal)
library(rasterVis)
library(maps)
library(rgeos)
library(tidyverse)
library(RColorBrewer)
library(tmap)

# view some color palettes
# display.brewer.all()
# rainbow color scheme
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) 

#setting smaller margins for plotting
par(mar=c(2,2,1,1))


```

#Load the threat layers
```{r}

all_spp <- raster("ca_curr_sp_rich.tif")


pollution <- raster("impact_pollution.tif")
shipping <- raster("impact_shipping.tif")



plot(pollution,col= cols)
plot(shipping,col=cols)


```


#Exploring the rasters
```{r}

hist(pollution, main = "Cumulative Pollution Frequency")
hist(shipping, main = "Cumulative Shipping Frequency")

#stack

ship_pol_stack <- stack(pollution, shipping)
plot(ship_pol_stack, col = cols)

```

#Crop to prepare to combine with species data later 

```{r}
pollution_crop <- crop(pollution, all_spp)
shipping_crop <- crop(shipping, all_spp)

#resample species to match resolution
spp_res <- resample(all_spp, pollution_crop, method = 'ngb', progress= 'text')

spp_ship_threat_stack <- stack(spp_res, pollution_crop, shipping_crop)
plot(spp_ship_threat_stack, col = cols)
```

#Reclassify zeros to NAs

```{r}
#Species
spp_recl <- reclassify(spp_res, rcl = c(-Inf, 0, NA))

#Shipping

ship_rcl <- reclassify(shipping_crop, rcl = c(-Inf, 0, NA))
hist(ship_rcl)

#Pollution 
pollution_rcl <- reclassify(pollution_crop, rcl = c(-Inf, 0, NA))
hist(pollution_rcl)

```

#Reclassify to top quantiles 

```{r}
#Species
#define the max value and the 0.8 quantile
spp_cutoff <- quantile(spp_recl, 0.8)
spp_maxVal <- cellStats(spp_recl,max)

#build reclassification matrix
rcl_mat <- c(-Inf, spp_cutoff,0,
             spp_cutoff,spp_maxVal,1)

#Reclassify the species layer 
spp_binary <- reclassify(spp_res,rcl=rcl_mat)

#Threats - Pollution 
pol_cutoff <- quantile(pollution_rcl, 0.8)
pol_maxVal <- cellStats(pollution_rcl,max)

rcl_mat1 <- c(-Inf, pol_cutoff,0,
             pol_cutoff,pol_maxVal,1)

pol_binary <- reclassify(pollution_rcl, rcl=rcl_mat1 )

binary_cols <- c("white", "tomato3")
plot(pol_binary, col=binary_cols, legend = F, main = "Top 20% Pollution Threats")

#Threats - shipping

ship_cutoff <- quantile(ship_rcl, 0.8)
ship_maxVal <- cellStats(ship_rcl,max)

rcl_mat2 <- c(-Inf, ship_cutoff,0,
             ship_cutoff,ship_maxVal,1)

ship_binary <- reclassify(ship_rcl, rcl=rcl_mat2)

binary_col_ship <- c("white", "aquamarine3")
plot(ship_binary, col=binary_col_ship, legend = F, main = "Top 20% Shipping Threats")
```

#Overlay Threat Layers 

```{r}

pol_ship_combo <- overlay(pol_binary,ship_binary, fun = function(x,y){x+y})

hotspots_sp <- overlay(pol_ship_combo, spp_binary, fun = function(x,y){x+y})
```

```{r}
#########################################
#Graphs, full extent
brks_ssp <- seq(0,3, length.out = 4)
ssp_cols <- c("white","coral2","firebrick3")

plot(pol_ship_combo, col = hotspots_sp_cols, legend = T, main  = "Top 20 Shipping and Pollution Threats")
map('world', fill = T, add = T, col = 'gray80') #this isn't working 


brks_hotspotssp <- seq(0,4, length.out = 5)
hotspot_cols <- c("white","goldenrod","coral2","firebrick")
plot(hotspots_sp, col = hotspot_cols, legend = T, main  = "Hotspots Based on Shipping and Pollution Threats")
map('world', fill = T, add = T) #this isn't working 


#Graphs, zoomed in on a particular location 


plot(pol_ship_combo, col = hotspots_sp_cols, ext = extent(-121,-117,32,35), legend = T, main  = "Top 20 Shipping and Pollution Threats")
map('world', fill = T, add = T) #this isn't working 



plot(hotspots_sp, col = hotspot_cols, ext = extent(-121,-117,32,35), legend = T, main  = "Hotspots Based on Shipping and Pollution Threats")
map('world', fill = T, add = T) #this isn't working 


```

